SELECT PRODUCT.NAME, PRODUCT_FILTER.NAME FROM BIKE_SHOP.`PRODUCT`
                                                  INNER JOIN PRODUCT_FILTER_LINK ON PRODUCT.ID = PRODUCT_FILTER_LINK.PRODUCT_ID
                                                  INNER JOIN PRODUCT_FILTER ON PRODUCT_FILTER_LINK.PRODUCT_FILTER_ID = PRODUCT_FILTER.ID
WHERE PRODUCT.ID = 1