<?php
	class AuthManager
	{
		private DatabaseConnector $db;
		
		public function __construct()
		{
			$db = new DatabaseConnector("user", "password", "BIKE_SHOP");
		}
		
		/**
		 * Checks a token to see whether or not it is valid
		 * @param string $token The token that was generated by /auth/login
		 * @return void
		 * @throws Exception If the token was invalid
		 */
		public function verifyToken(string $token): bool
		{
			// Get token object from string
			$parts = explode('.', $token);
			if (count($parts) != 3)
			{
				throw new Exception("Invalid token provided. Please login again");
			}
			
			$header = $parts[0];
			$payload = $parts[1];
			$receivedSignature = $parts[2];
			
			// Verify signature by re-hashing the header and payload together using SECRET_KEY which only this
			// application will know about; only this application will be able to generate a valid
			// signature in the first place
			$expectedSignature = hash_hmac('sha256', $header . '.' . $payload, JwtToken::SECRET_KEY, true);
			$expectedSignature = str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($expectedSignature));
			
			if ($receivedSignature != $expectedSignature)
			{
				throw new Exception("Invalid token provided. Please login again");
			}
			
			$payload = base64_decode($payload);
			$header = base64_decode($header);
			
			// Check expiry date. If it is passed the expiry date, reroute to /auth/login and clear the token cookie
			$jsonPayload = json_decode($payload, true);
			if (!array_key_exists('exp', $jsonPayload) || empty($jsonPayload['exp']))
			{
				throw new Exception("Token has expired. Please login again");
			}
			
			return true;
		}
	}